app/books/api/urls.py
from books.api import views
from rest_framework.routers import DefaultRouter

app_name = 'books-api'

router = DefaultRouter()

router.register('books', views.BookModelViewSet, basename='book')
router.register('author', views.AuthorModelViewSet, basename='author')
router.register('category', views.CategoryModelViewSet, basename='category')


urlpatterns = router.urls

app/books/urls.py
from django.urls import path
from books import views

app_name = "books"

urlpatterns = [
    # book
    path('list/', views.BookList.as_view(), name='list'),
    path('list/my-books/', views.MyBooksList.as_view(), name='my-books'),
    path('list/my-requested-books/', views.MyRequestedBooks.as_view(), name='my-requested-books'),
    path('list/requested-books/', views.RequestedBooks.as_view(), name='requested-books'),
    path('requested-books/confirm/<int:request_id>/', views.RequestBookConfirm.as_view(),
         name='requested-books-confirm'),
    path('requested-books/reject/<int:request_id>/', views.RequestBookReject.as_view(),
         name='requested-books-reject'),
    path('requested-books/sent-via-email/<int:request_id>/', views.RequestBookSentViaEmail.as_view(),
         name='sent-via-email'),
    path('requested-books/book-received/<int:request_id>/', views.RequestBookReceivedBook.as_view(),
         name='book-received'),
    path('requested-books/sent-back-to-owner/<int:request_id>/', views.RequestBookSentBackToOwner.as_view(),
         name='sent-back-to-owner'),
    path('requested-books/owner-received/<int:request_id>/', views.RequestBookOwnerReceivedBack.as_view(),
         name='owner-received'),
    path('create/', views.BookCreate.as_view(), name='create'),
    path('update/<int:pk>/', views.BookUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', views.BookDelete.as_view(), name='delete'),
    path('download/csv/', views.DownloadCSVBookView.as_view(), name='download-csv'),
    path('download/xlsx/', views.DownloadXlSXBookView.as_view(), name='download-xlsx'),
    path('create/book/request/<int:book_id>/', views.RequestBookCreate.as_view(), name='create-book-request'),
    path('details/<int:pk>/', views.BookView.as_view(), name='details'),


    # author
    path('author/list/', views.AuthorList.as_view(), name='author-list'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/update/<int:pk>/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/delete/<int:pk>/', views.AuthorDelete.as_view(), name='author-delete'),
]

app/booksharing/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path, re_path
from accounts.views import MyProfileView, ContactUsView, SignUpView, ActivateView
from books import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


API_V1_PREFIX = 'api/v1/'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('books/', include('books.urls')),

    path('', views.Index.as_view(), name='index'),

    path('accounts/my-profile/', MyProfileView.as_view(), name='my-profile'),
    path('accounts/contact-us/', ContactUsView.as_view(), name='contact-us'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/activate/<uuid:username>/<token>/', ActivateView.as_view(), name='activate'),

    # API
    path(API_V1_PREFIX, include('books.api.urls')),
    path(f'{API_V1_PREFIX}token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_V1_PREFIX}token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns += [
   re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar # noqa

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
    )

app/books/models.py
from django.db import models
from books import model_choices as mch
from django.templatetags.static import static
from django.core.cache import cache


def book_upload_coverage(instance, filename):
    if Book.objects.all().count() == 0:
        book_id = 1
    else:
        book_id = Book.objects.last().id + 1
    path = f'coverage/{book_id}/{filename}'
    return path


class Author(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    country = models.CharField(max_length=128)
    gender = models.CharField(max_length=6)
    native_language = models.CharField(max_length=128)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Book(models.Model):
    title = models.CharField(max_length=128)
    publish_year = models.PositiveSmallIntegerField()
    review = models.CharField(max_length=512)
    condition = models.PositiveSmallIntegerField()
    category = models.ForeignKey('books.Category', on_delete=models.CASCADE,
                                 null=True, default=None)
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE,
                             null=True, default=None)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL,
                               null=True, default=None)
    coverage = models.FileField(null=True, default=None, upload_to=book_upload_coverage)

    def __str__(self):
        return f"{self.id} {self.title} {self.author_id}"

    @property
    def coverage_url(self):
        if self.coverage:
            return self.coverage.url
        else:
            return static('media/coverage/default/image.jpg')


class RequestBook(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    recipient = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    status = models.PositiveSmallIntegerField(choices=mch.REQUEST_STATUSES)


class Log(models.Model):
    path = models.CharField(max_length=128)
    method = models.CharField(max_length=128)
    time = models.PositiveIntegerField()


class Category(models.Model):
    name = models.CharField(max_length=64)

    CACHE_OBJECTS_LIST = 'CategoryList'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self._refresh_cache_objects_list()

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        self._refresh_cache_objects_list()

    @classmethod
    def _refresh_cache_objects_list(cls):
        from books.api.serializers import CategorySerializer  # noqa

        cache.delete(cls.CACHE_OBJECTS_LIST)
        queryset = cls.objects.all()
        serializer = CategorySerializer(queryset, many=True)
        response_data = serializer.data
        cache.set(Category.CACHE_OBJECTS_LIST, response_data, 60 * 60 * 24 * 7)

    def __str__(self):
        return self.name

app/books/forms.py
from django import forms
from books.models import Book, Author


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'author',
            'title',
            'publish_year',
            'review',
            'condition',
            'coverage',
        )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user

        if commit:
            instance.save()

        return instance


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = (
            'first_name',
            'last_name',
            'country',
            'gender',
            'native_language',
            'date_of_birth',
            'date_of_death',
        )

app/books/api/views.py
from rest_framework import viewsets, filters
from django_filters.rest_framework import DjangoFilterBackend
from books.api.filters import BookFilter, AuthorFilter
from books.api.serializers import BookSerializer, AuthorSerializer, CategorySerializer
from books.models import Book, Author, Category
from rest_framework.response import Response
from django.core.cache import cache

# class BookList(generics.ListCreateAPIView):
#     queryset = Book.objects.all()
#     serializer_class = BookSerializer
#
#
# class BookInstanceView(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Book.objects.all()
#     serializer_class = BookSerializer


class BookModelViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    ordering_fields = ['condition', 'title']
    filterset_class = BookFilter
    # filterset_fields = ['condition']
    # filterset_fields = {
    #     'title': ['icontains', 'exact'], # filter(title='awda'), filter(title__exact='awda')
    #     'condition': ['gt', 'gte', 'lt', 'lte'],
    # }


class AuthorModelViewSet(viewsets.ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    ordering_fields = ['full_name', 'country']
    filterset_class = AuthorFilter


class CategoryModelViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = ()
    pagination_class = None

    def list(self, request, *args, **kwargs):

        response_data = cache.get(Category.CACHE_OBJECTS_LIST)
        if response_data is not None:
            return Response(response_data)

        queryset = self.get_queryset()
        serializer = self.get_serializer(queryset, many=True)
        response_data = serializer.data
        cache.set(Category.CACHE_OBJECTS_LIST, response_data, 60 * 60 * 24 * 7)  # move to consts

        return Response(response_data)

app/books/templates/books/author_confirm_delete.html
{% extends 'base.html' %}

{% block content%}
<div class="row">
            <div class="col-12">
                <p class="h4">Do you really want delete author with id: {{ object.pk }}</p>

                <form method="post">{% csrf_token %}
                    <p class="h6">Are you sure you want to delete author "{{ object.first_name }} {{ object.last_name }}"?</p>
                    <input type="submit" class="btn btn-success" value="Confirm">
                </form>
          </div>
</div>
{% endblock content%}

app/books/templates/books/author_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content%}
<div class="row">
            <div class="col-4">
                <h1>{{ message }}</h1>

                <p class="h4">Form to add new author</p>

                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
                <br>
                {% if form.instance.id and request.user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'books:author-delete' form.instance.id %}">
                        DELETE</a>
                {% endif%}
            </div>
</div>
{% endblock content%}

app/books/templates/books/author_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
        <div class="col">
            {% if  request.user.is_authenticated %}
                    <a class="btn btn-success" href="{% url 'books:author-create' %}">Author Create</a>
            {% endif%}

        <table class="table table-striped font-size-12">
                <tr>
                    <th>№</th>
                    <th>ID</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Country</th>
                    <th>Gender</th>
                    <th>Native language</th>
                    <th>Date of birth</th>
                    <th>Date of death</th>
                    {% if  request.user.is_authenticated %}
                    <th></th>
                    {% endif%}
                </tr>

                {% for author in author_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ author.id }}</td>
                        <td>{{ author.first_name }}</td>
                        <td>{{ author.last_name }}</td>
                        <td>{{ author.country }}</td>
                        <td>{{ author.gender }}</td>
                        <td>{{ author.native_language }}</td>
                        <td>{{ author.date_of_birth }}</td>
                        <td>{{ author.date_of_death }}</td>
                        {% if  request.user.is_authenticated %}
                        <td><a class="btn btn-primary" href="{% url 'books:author-update' author.pk %}">Edit</a></td>
                        {% endif%}
                    </tr>
                {% endfor %}
            </table>
        </div>
</div>

{% endblock content %}

app/books/templates/books/book_confirm_delete.html
{% extends 'base.html' %}

{% block content%}
<div class="row">
            <div class="col-12">
                <p class="h4">Do you really want delete book with id: {{ object.pk }}</p>

                <form method="post">{% csrf_token %}
                    <p class="h6">Are you sure you want to delete book "{{ object.title }}"?</p>
                    <input type="submit" class="btn btn-success" value="Confirm">
                </form>
          </div>
</div>
{% endblock content%}

app/books/templates/books/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content%}
    <div class="row">
                <div class="col-4">
                    <p class="h3">{{ object.title }}</p>
                    {% if  book.coverage.url == '/media/True' %}
                    <img width="150" height="200"
                         src="{% static 'img/index.png' %}"
                         data-holder-rendered="true">
                    {% else %}
                    <img width="150" height="200"
                         src="{{ book.coverage_url }}"
                         data-holder-rendered="true">
                    {% endif%}

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                    </form>

                    <br><br>
                    <p class="h5">By {{ object.author.first_name }} {{ object.author.last_name }}</p>
                    <p class="h6">{{ object.category }}</p>
                    <p class="h6">{{ object.review }}</p>
                    <p class="h6">Publish in {{ object.publish_year }}, condition {{ object.condition }}</p>

                </div>
    </div>
{% endblock content%}

app/books/templates/books/book_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content%}
    <div class="row">
                <div class="col-4">
                    <h1>{{ message }}</h1>
                    <p class="h4">Form to add new book</p>

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-success">Submit</button>
                    </form>

                    {% if form.instance.id and request.user.is_authenticated%}
                        <a class="btn btn-primary" href="{% url 'books:delete' form.instance.id %}">DELETE</a>
                    {% endif%}
                </div>
    </div>
{% endblock content%}

app/books/templates/books/book_list.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
        <div class="col">
            <a class="btn btn-success" href="{% url 'books:download-csv' %}">Download CSV</a>
            <a class="btn btn-success" href="{% url 'books:download-xlsx' %}">Download XLSX</a>

            <table class="table table-striped font-size-12">
                    <tr>
                        <th>№</th>
                        <th>ID</th>
                        <th>Author Name</th>
                        <th>Title</th>
                        <th>Publish Year</th>
                        <th>Review</th>
                        <th>Condition</th>
                        <th>Category</th>
                        <th></th>
                        <th></th>
                    </tr>

                    {% for object in object_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ object.id }}</td>
                            <td>
                                {{ object.author.first_name }}
                                {{ object.author.last_name }}
                            </td>
                            <td>{{ object.title }}</td>
                            <td>{{ object.publish_year }}</td>
                            <td>{{ object.review }}</td>
                            <td>{{ object.condition }}</td>
                            <td>{{ object.category }}</td>
                            <td><a class="btn btn-primary" href="{% url 'books:create-book-request' object.id %}">
                                Request Book</a></td>
                            <td><a class="btn btn-primary" href="{% url 'books:details' object.pk %}">
                                Details</a></td>
                        </tr>
                    {% endfor %}
                </table>
        </div>
</div>

{% endblock content %}

app/books/templates/books/my_books.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
        <div class="col">
            {% if  request.user.is_authenticated %}
                <a class="btn btn-success" href="{% url 'books:create' %}">Books Create</a>
            {% endif%}

            <table class="table table-striped font-size-12">
                    <tr>
                        <th>№</th>
                        <th>ID</th>
                        <th>Author Name</th>
                        <th>Title</th>
                        <th>Publish Year</th>
                        <th>Review</th>
                        <th>Condition</th>
                        {% if  request.user.is_authenticated %}
                            <th></th>
                        {% endif%}
                        <th>Category</th>
                    </tr>

                    {% for object in object_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ object.id }}</td>
                            <td>
                                {{ object.author.first_name }}
                                {{ object.author.last_name }}
                            </td>
                            <td>{{ object.title }}</td>
                            <td>{{ object.publish_year }}</td>
                            <td>{{ object.review }}</td>
                            <td>{{ object.condition }}</td>
                            {% if  request.user.is_authenticated %}
                                <td><a class="btn btn-primary" href="{% url 'books:update' object.pk %}">
                                    Edit</a></td>
                            {% endif%}
                            <td>{{ object.category }}</td>
                        </tr>
                    {% endfor %}
            </table>
        </div>
</div>
{% endblock content %}

app/books/templates/books/requestbook_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
        <div class="col">
            <table class="table table-striped font-size-12">
                <tr>
                    <th>№</th>
                    <th>ID</th>
                    <th>Book</th>
                    <th>Created</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>

                {% for object in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ object.id }}</td>
                        <td>{{ object.book.title }}</td>
                        <td>{{ object.created }}</td>
                        <td>{{ object.get_status_display }}</td>
                        <td>
                            {% if object.status == mch.STATUS_SENT_TO_RECIPIENT %}
                                <a class="btn btn-primary" href="{% url 'books:book-received' object.id %}">
                                    I got the book!</a>
                            {% elif object.status == mch.STATUS_RECIPIENT_RECEIVED_BOOK %}
                                <a class="btn btn-primary" href="{% url 'books:sent-back-to-owner' object.id %}">
                                    Sent back to owner</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
</div>
{% endblock content %}

app/books/templates/books/requested_book_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
        <div class="col">
            <table class="table table-striped font-size-12">
                <tr>
                    <th>№</th>
                    <th>ID</th>
                    <th>Book</th>
                    <th>Created</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>

                {% for object in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ object.id }}</td>
                        <td>{{ object.book.title }}</td>
                        <td>{{ object.created }}</td>
                        <td>{{ object.get_status_display }}</td>
                        <td>
                            {% if object.status == mch.STATUS_IN_PROGRESS %}
                                <a class="btn btn-primary" href="{% url 'books:requested-books-confirm' object.id %}">
                                    Confirm</a>|
                                <a class="btn btn-primary" href="{% url 'books:requested-books-reject' object.id %}">
                                    Reject</a>
                            {% elif object.status == mch.STATUS_CONFIRMED %}
                                <a class="btn btn-primary" href="{% url 'books:sent-via-email' object.id %}">
                                    Sent Via Email</a>
                            {% elif object.status == mch.STATUS_SENT_BACK_TO_OWNER %}
                                <a class="btn btn-primary" href="{% url 'books:owner-received' object.id %}">
                                    I received book back!</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
</div>
{% endblock content %}